# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: starefossen/ruby-node:latest
    steps:
      - checkout
      - run: apt-get -y install sudo
      - run: sudo apt-get -y install software-properties-common
      - run: sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
      - run: sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      - run: sudo apt-get -y update
      - run: sudo apt-get -y --allow-unauthenticated install google-chrome-stable
      - run: sudo apt-get install -y openjdk-8-jdk
      # - run: 
      #     |
      #     sudo apt-get -y  --allow-unauthenticated install oracle-java8-installer
      #     echo yes

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --without production --jobs=4 --retry=3 --path vendor/bundle
            npm install

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
        
      # Database setup
      - run: bundle exec rake db:create db:schema:load --trace
      - run: bundle exec rake db:migrate
      # Application.js setup
      - run: npm run build
      # run tests!
      - run:
          name: run tests
          command: |
            bundle exec rake test 
            npm run unit
            bundle exec rails s -d 
            # npm run e2e --verbose
            kill `cat tmp/pids/server.pid`


           
